### ISSUE TITLE
Breaking block while moving

### ISSUE THREAD

**Issue by AppPhil** [baseball435/TerraLegion#18]
When I use the joystick to move and the mouse moves out of the joystick circle I accidentally destroy blocks.

This video shows what I mean (sorry for the bad quality):
[video.zip](https://github.com/jmrapp1/TerraLegion/files/353853/video.zip)

Edit:
It's not only destroying blocks. You can also open the inventory and stuff like that.

**Comment by jmrapp1** [comment]
Yes the reason that this is happening is because of merge #16. I meant to change that last night, but it completely slipped my mind. The problem arises from [this change](https://github.com/jmrapp1/TerraLegion/pull/16/commits/141c63e79a8079f591f7f90a883a4cab68403b00) he made. He removed the `else if` statement and changed it to an `if` statement, but it should be an `else if` statement. I've taken care of this in 1fa6079829c397a5fb581d9d5f8e8aea24c58896.
